server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**

        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**

        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**

        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**

        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**

        - id: index-service  # 搜索服务路由
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api

        - id:  cart-service   #购物车微服务
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api

        - id:  pay-service   #支付微服务
          uri: lb://pay-service
          predicates:
            - Path=/api/pay/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # 重写前缀，去掉/api





  application:
    name: gamll-gateway

gmall:
  jwt:
    pubKeyPath: C:\\tmp\\project02\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
